// mapTemplate.js
const fs = require('fs');

function savePerplexityResultToFile(resultText, filename = 'output_result.js') {
  const headerComment = `/**\n * Generated by Perplexity AI\n * ${new Date().toISOString()}\n */\n\n`;
  const fullText = headerComment + resultText;

  fs.writeFileSync(filename, fullText, 'utf-8');
  console.log(`✅ 결과 저장 완료: ${filename}`);
}

module.exports = { savePerplexityResultToFile };
